#!/usr/bin/env bash
# One argument expected:
#    1: Name of the slice

if [[ -n "$1" ]]; then
    FS_ID=$1
else
    echo "Must specify first parameter (FlowSpace ID)"
    ERR=1
fi

if [[ -z "$ERR" ]]; then
    #curl http://$RYU_API_HOST:$RYU_API_PORT/v1.0/flowvisor/"$SLICE_NAME"_"$CTRL_IP_ADDR"_"$CTRL_PORT_NUM" -X POST
    fvctl --url=https://localhost:8085 --passwd-file=/usr/etc/flowvisor/passFile removeFlowSpace $FS_ID
fi
